### ISSUE TITLE
Unpublished articles are still available on Google search results

### ISSUE THREAD

**Issue by jeffasseur** [sulu/SuluHeadlessBundle#141]
When we unpublish an article, we can still find the article when we search on it on Google. This seems not really correct.

**Comment by alexander-schranz** [comment]
@jeffasseur 

PS: The redirects bundle support to create a 410 entry into the Redirect Table which throw then a HttpException with 410 Gone response. https://github.com/sulu/SuluRedirectBundle?tab=readme-ov-file#different-statuses 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410. If this is good or bad for google search bot SEO will have different answers. By default Sulu returns 404 for unpublished or not existing articles or pages.

The 410 feature only happens when a document got removed not unpublished.
