### ISSUE TITLE
Add support for HttpCache

### ISSUE THREAD

**Issue by drakulis** [sulu/SuluHeadlessBundle#50]
It looks that headless Sulu doesn't support cache at all and every request is processed by the code.

Configuration:
```
sulu_http_cache:
    proxy_client:
        symfony:
            enabled: true
    cache:
        max_age:              3600
        shared_max_age:       3600
    debug:
        enabled: true
    tags:
        enabled: true
```
with such configuration headers of sulu response are like:
Header | Value
-- | --
Server: | nginx/1.19.2
Content-Type: | application/json
Transfer-Encoding: | chunked
Connection: | keep-alive
Cache-Control: | no-cache, private
Date: | Tue, 29 Sep 2020 13:54:37 GMT-1s
X-Cache-Debug: | 1
X-Cache-Tags: | 4230128b-edf8-4a1f-8d7a-47f942e35f7e
X-Generator: | Sulu/2.1.0-RC1
X-Robots-Tag: | noindex
X-Symfony-Cache: | GET /pl/inspiracje-1-1.json: miss
X-Cache: | MISS

**Comment by alexander-schranz** [comment]
@drakulis Thanks for report it seems the following code is missing:

https://github.com/sulu/sulu/blob/886e415e4b0d243ca18724391d98528bd5f28e23/src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php#L98-L100

We should change the code here to write the a `$response` variable instead of returns: 

https://github.com/sulu/SuluHeadlessBundle/blob/70e1f3010fc226791c687f8aa00662c55f1faa97/Controller/HeadlessWebsiteController.php#L49-L58

And call that service.

Do you want to create a PR for this?

**Comment by drakulis** [comment]
@alexander-schranz here: https://github.com/sulu/SuluHeadlessBundle/pull/51
